### ISSUE TITLE
how to reproduce the result of LoRA

### ISSUE THREAD

**Issue by TracyGuo2001** [MohammadrezaBanaei/LoRA-XS#5]
just remove `find_and_initialize()` in `main_glue_no_svd.py`? what about the param in `run_glue_no_svd.py` especially the cls_lr? Thanks for your work and reply!

**Comment by MohammadrezaBanaei** [comment]
Hi!
for any of LoRA-XS experiments, removing `find_and_initialize()` would make the training equivalent to training LoRA. For reproducing LoRA results, I suggest looking into the Table 9 of LoRA paper.
Regarding `cls_lr`: LoRA authors use the same learning rate as the LoRA modules for the classifier, so you can set it to the same LR as LoRA learning rate.
